name: peliculas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.8.1

dependencies:
  card_swiper: ^3.0.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_rating_bar: ^4.0.1
  http: ^1.2.2
  image_picker: ^1.2.1
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cardswiper/
    - assets/
